### ISSUE TITLE
Query nested data doesn't seem to work

### ISSUE THREAD

**Issue by gerrywastaken** [ankane/searchkick#1053]
I'm a bit confused. The docs say:

> To query nested data, use dot notation.
> 
> `User.search "san", fields: ["address.city"], where: {"address.zip_code" => 12345}`

However when I do this, a nested query is not generated. I did a search in the code base to see how this should work, but the only place where I can see the "nested" keyword even being used (outside of tests and mapping) is for querying nested conversions:

https://github.com/ankane/searchkick/blob/master/lib/searchkick/query.rb#L387

**Comment by ankane** [comment]
Hey @gerrywastaken, `nested` queries aren't required for this. See https://github.com/ankane/searchkick/blob/cc0d26309cf49bf4ddcf8b2fadf2529dac353a72/test/where_test.rb#L217

**Comment by will-r** [comment]
Thanks, @ankane. That was useful. I have a similar query on a nested array field that was returning no results, and after taking out the `nested` business to reduce it to a simple inner field, it works fine.

In my case that's ideal because the nested data is basically flat (I'm expanding the occurrences of an event). If they had more composition I'd still be worried about the nesting.

Range construction works nicely too:

```
          "range": {
            "occurrence.start": {
              "from": "2018-01-01",
              "include_lower": true,
              "to": "2018-01-30",
              "include_upper": true
            }
          }
```

**Comment by gerrywastaken** [comment]
@ankane sorry for not responding earlier. Ah I see, I thought this meant it was for querying of nested data instead of just standard object fields. I understand now.
