### ISSUE TITLE
Can't set up with Heroku

### ISSUE THREAD

**Issue by mhluska** [ankane/searchkick#1063]
I can't for the life of me get this set up with [Heroku](https://github.com/ankane/searchkick#heroku) by following the readme. It works fine locally with a local elasticsearch server running.

I first tried the SearchBox integration and kept getting an `access denied` error. I traced through the code and it's likely an issue on Searchly's end. I contacted their support, still waiting to hear back. This one is most desirable for me because it has a free tier.

Next I tried Bonsai and had a similar issue. 403 Forbidden or something along those lines.

Then I tried the Elastic Cloud integration. Similar issue:

```
Elasticsearch::Transport::Transport::Errors::Unauthorized: [401] {"error":{"root_cause":[{"type":"security_exception","reason":"action [indices:admin/get] requires authentication","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"action [indices:admin/get] requires authentication","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401
```

Finally I tried going directly to Amazon. This one seemed promising but I couldn't get access control set up properly with Heroku (VPC? IP address list?). I got a 443 when I run `heroku run rake searchkick:reindex CLASS=Video`

`Faraday::TimeoutError: Failed to open TCP connection to <url>`

Here's my Searchkick config:

```
Searchkick.client_options = {
  retry_on_failure: true,
  transport_options: { request: { timeout: 250 }}
}

Searchkick.aws_credentials = {
  access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
  region: 'us-west-1'
}
```

And gems:

```
gem 'searchkick'
gem 'elasticsearch' # Required by `searchkick`
gem 'faraday_middleware-aws-signers-v4' # Required by `searchkick`
```

I'm not really sure what to try next. Have you guys got this running with Heroku + Searchly/Bonsai/Elastic Cloud before?

**Comment by mhluska** [comment]
I finally got this working with Elastic Cloud. Here's what I did:

First do what the readme says:

```
heroku addons:create foundelasticsearch
heroku config:set ELASTICSEARCH_URL=`heroku config:get FOUNDELASTICSEARCH_URL`
```

Then log in to the Elastic Cloud console:

```
heroku addons:open foundelasticsearch
```

Then follow what this SO answer says: https://stackoverflow.com/a/41996068/659910
Basically, reset password for main `elastic` user, enable Kibana, go into Kibana dashboard and add a custom user. In my case I added user `mhluska` with password `password123` (example).

Then add this to an initializer:

```
Searchkick.client_options = {
  transport_options: {
    headers: {
      Authorization: "Basic #{ENV['FOUNDELASTICSEARCH_TOKEN']}"
    }
  }
}
```

That's actually the redacted version. Here's my full initializer but I'm not sure if the other config settings matter:

```
Searchkick.client_options = {
  retry_on_failure: true,
  transport_options: {
    request: {
      timeout: 250
    },
    headers: {
      Authorization: "Basic #{ENV['FOUNDELASTICSEARCH_TOKEN']}"
    }
  },
}
```

Now open up `irb` in the console and create a token:

```
require 'base64'
Base64.strict_encode64('mhluska:password123')
```

It's important to use `strict_encode` to avoid newlines. Save that token in Heroku:

```
heroku config:set FOUNDELASTICSEARCH_TOKEN='<your token>'
```

Now you can finally do `heroku run rake searchkick:reindex CLASS=<your model>` as the readme suggests.

**Comment by donnfelker** [comment]
@mhluska thank you so much for this. I had the exact same problem and your instructions were crystal clear. 👏

**Comment by ankane** [comment]
Hey @mhluska, thanks for the detailed report. I just tested all the Heroku integrations and here's what I found:

1. Bonsai works with current instructions
2. SearchBox does not work at all
3. Found requires you to retrieve your password and add it to your `ELASTICSEARCH_URL` (you don't need to modify your `Searchkick.client`)

I've updated the readme to reflect all this. Please let me know if it's clear. For AWS, my guess is your VPC or security groups weren't configured correctly.

**Comment by jamesarobbo** [comment]
@ankane I have a similar issue

The below happens when trying to reindex

`Elasticsearch::Transport::Transport::Errors::NotAcceptable: [406] {"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
/app/vendor/bundle/ruby/2.3.0/gems/elasticsearch-transport-5.0.0/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
/app/vendor/bundle/ruby/2.3.0/gems/elasticsearch-transport-5.0.0/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
/app/vendor/bundle/ruby/2.3.0/gems/elasticsearch-transport-5.0.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/app/vendor/bundle/ruby/2.3.0/gems/elasticsearch-transport-5.0.0/lib/elasticsearch/transport/client.rb:128:in `perform_request'
/app/vendor/bundle/ruby/2.3.0/gems/elasticsearch-api-5.0.0/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/app/vendor/bundle/ruby/2.3.0/gems/elasticsearch-api-5.0.0/lib/elasticsearch/api/actions/indices/create.rb:86:in `create'
/app/vendor/bundle/ruby/2.3.0/gems/searchkick-2.5.0/lib/searchkick/index.rb:14:in `create'
/app/vendor/bundle/ruby/2.3.0/gems/searchkick-2.5.0/lib/searchkick/index.rb:184:in `create_index'
/app/vendor/bundle/ruby/2.3.0/gems/searchkick-2.5.0/lib/searchkick/index.rb:233:in `reindex_scope'
/app/vendor/bundle/ruby/2.3.0/gems/searchkick-2.5.0/lib/searchkick/model.rb:72:in `searchkick_reindex'
/app/vendor/bundle/ruby/2.3.0/gems/searchkick-2.5.0/lib/searchkick/tasks.rb:9:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
/app/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
Tasks: TOP => searchkick:reindex`
