### ISSUE TITLE
[Idea] Custom functions for function_score

### ISSUE THREAD

**Issue by abraaomiranda** [ankane/searchkick#1294]
Hi @ankane ,

I have 2 different scenarios that would be easier to solve if there was a way to pass a custom `function_score` to my searchkick query.

**1 - Random Sort**
I want to randomize a filtered search:

```
{
  query: {
    function_score: {
      query: ... # filtering results
      random_score: {}
    }
  }
}
```

**2 - Sort by ids**
I want to sort my result by an array of ids, still with the possibility of filtering it:

```
{
  query: {
    function_score: {
      query: ... # filtering results
      script_score: {
        script: {
          params: { ids: ids },
          source: '-params.ids.indexOf(Integer.parseInt(doc["_id"].value))'
        }
      }
    }
  }
}
```

Since the boost prefixed options work with `function_score`, it should be easy to make a `:custom_score` option that would mount the `function_score` inside the `body` with the option value.

**Comment by ankane** [comment]
Hey @abraaomiranda, thanks for the suggestion. I'm hesitant to mix ES syntax and Searchkick syntax (any more than it already is), especially since I don't think these cases are very common. There's already a pretty flexible way to do this with the block form of advanced search: https://github.com/ankane/searchkick#advanced-search
