### ISSUE TITLE
Support for cross fields

### ISSUE THREAD

**Issue by jume-dev** [ankane/searchkick#1444]
Hi there,
First of all, a big fat thanks for your work on this project. I played with it for the last few hours and I had a blast trying things out.
Sadly, as far as I could see, there is no support for the cross-field search feature of elastic search, right? I only found an old issue(https://github.com/ankane/searchkick/issues/707) asking for a new discussion if someone needed that feature.

So, well, I'd need that feature, because I want to enable my users to narrow their search by adding more keywords. It's basically an address search and the user should be able to enter for example a street name and a city and should get addresses where these match.

As far as I understood elastic search, the cross-field feature should be the solution here, but I am also open to other suggestions here.
Thanks for reading and have a nice day,
Robert

**Comment by ankane** [comment]
Hey @jume-dev, you'll need to use [Advanced Search](https://github.com/ankane/searchkick#advanced-search) to use Elasticsearch's cross field functionality. I was hoping to make it the default for Searchkick at some point, but it doesn't currently support misspellings (and I don't currently want to support a new non-default search pattern).

An alternative is to create a combined field in the `search_data` method and search on that.

**Comment by jume-dev** [comment]
Alright, thanks for your answer. I used search_data, yes and it works quite well. But I wasn't sure what the implication is for the system. I couldn't find an answer if there are any downsides to simple combining all fields into one

**Comment by ankane** [comment]
From my understanding, the primary downside is you're unable to boost an individual field when they're combined.

**Comment by jume-dev** [comment]
Alright, makes totally sense, thank you.

**Comment by 9mm** [comment]
@ankane do you happen to know if i have a combined field with everything it is, is there still a way I can get highlighting on my individual non-combined fields? (the reason is, theyre actually displayed separately in the UI .. ie split on different lines, in parenthesis, etc). 

Im trying to get it so one word can match one field, and one word can match another field.

If I use 'OR' its way too open ended and not desireable as adding words increases results not decreases.

I have all my fields indexed into appropriate columns (model name, model number, model alternate number)

but people often search as ...

"<name> <number> <id>" or some combination of that'

And in the UI it as shown as:

```
[Name] (id)
<number>
```

So its not enough to just show the indexed field

**Comment by bholzer** [comment]
I know this issue has been closed for a while now, but I'd like to ask for a reconsideration here.

I will argue that when searching with multiple terms against multiple fields, the expected behavior in most cases is that multiple fields should be able to match, like cross fields. This seems to be a common request.

I recognize that a new non-default search pattern may be a significant hurdle and that there are some alternatives. However, I find the alternatives to be problematic:

- The combined field workaround must be reindexed if you ever want to search by a new field. This field may also be contrived for some cases. It is a pretty inflexible mechanism.
- Using advanced search to do a cross field or combined field query is more of an escape hatch which loses some of the convenience and clean syntax that searchkick provides. I am still having to build queries myself to accomplish this.

Searchkick is excellent and I am going to use it either way, but supporting cross fields and/or combined fields would be a big win
