### ISSUE TITLE
"index_not_found_exception" with Rails parallel tests when inheritance introduced

### ISSUE THREAD

**Issue by benaldred** [ankane/searchkick#1542]
I have the following index 

```ruby
class Person < ApplicationRecord
  searchkick word_start: [:name], word_middle: [:email], callbacks: :async

  def self.search(params, opts = {})
    # does setup then calls
    # searchkick_search(...)
  end
end
```

This was running well with the Rails parallel tests

```ruby
class ActiveSupport::TestCase
  parallelize_setup do |worker|
    Searchkick.index_suffix = worker

    Person.reindex

    Searchkick.disable_callbacks
  end
end
```

Then I introduced a subclassed model

```ruby
class Foo < Person
  def self.search(params, opts = {})
    # does Foo specific setup then calls
    # Person.search
  end
end
```

The tests now have broken. I'm getting messages like

```
[404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [people_test_20220215113508967]","index_uuid":"HwTJI99mTUSbFvoreHv1ZA","index":"people_test_20220215113508967"}],"type":"index_not_found_exception","reason":"no such index [people_test_20220215113508967]","index_uuid":"HwTJI99mTUSbFvoreHv1ZA","index":"people_test_20220215113508967"},"status":404} (Elasticsearch::Transport::Transport::Errors::NotFound)
````

I can run the tests on my CI in as it runs in one processor or if I remove the subclassed model. 

If I remove the `parallelize_setup` setup it runs some of the time and other times it errors

**Comment by ankane** [comment]
Hey @benaldred, check out #1534.

**Comment by ankane** [comment]
Just released Searchkick 5, which should fix this (let me know if it doesn't).

**Comment by tbcooney** [comment]
I'm facing a similar issue as described here and in #1534. I've been digging into it this after noticing our CI failing about 50% of the time (just to be clear, as @benaldred describes it works _sometimes_ and works in a single process).

I tried to setup and outline below the same setups as #1534 and #1542; the `config/environments/test.rb` file has `config.eager_load = true` which would be reflective of a true CI environment. Tests are also parallelized by default. I've also added a `FOO` and `BAR` print method to display that the Facility model is loaded before `parallelize_setup` is run.

Running the test defined below, **the expected behaviour** is to return the record defined in `test/fixtures/facilities.yml`, however the results are empty. Just to be clear, if I tune down the workers to `PARALLEL_WORKERS=1` then results do contain the record.

If I print out the index suffix and name in the failing test case to see what it outputs:

```
p Searchkick.index_suffix
p Facility.search_index.name

=> 1
=> "facilities_test_1"
```

The output matches the search index tailing the test logs (so I can confirm that the search is being performed against the correct index):

```
Facility Search (10.1ms)  facilities_test_1/_search {"query":{"match_all":{}},"timeout":"11s","_source":false,"size":10000}
```

-------

```
# Gemfile
gem "elasticsearch", "< 7.14"
gem 'searchkick', '~> 5.0', '>= 5.0.2'
```

```
# test_helper.rb
class ActiveSupport::TestCase
  # Run tests in parallel with specified workers
  parallelize(workers: :number_of_processors)

  parallelize_setup do |worker|
    puts "FOO"
    Searchkick.index_suffix = worker

    Facility.reindex
    
    Searchkick.disable_callbacks
  end
  
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  fixtures :all
end
```

```
# app/models/facility.rb
class Facility < ApplicationRecord
  puts "BAR"
  
  searchkick

  def search_data
    {
      name: name
    }
  end
end
```

```
# test/models/facility_test.rb
require "test_helper"

class FacilityTest < ActiveSupport::TestCase
  setup do
    Searchkick.enable_callbacks
  end

  test "search results" do
    print "Results: #{Facility.search("*").to_a}"
  end
end
```

Following is the test results:
```
home@MacBook-Pro-3 % PARALLEL_WORKERS=2 bin/rails test test/models/facility_test.rb
BAR
Running 12 tests in parallel using 2 processes
Run options: --seed 20506

# Running:

FOO
FOO
Results: [].

Finished in 3.875251s, 0.2580 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by ankane** [comment]
From my understanding, fixtures don't run callbacks, so you'll need to reindex manually after they've been created.

**Comment by tbcooney** [comment]
> From my understanding, fixtures don't run callbacks, so you'll need to reindex manually after they've been created.

Ah, you're right -- fixtures do not use callbacks. I presume that it is quicker to load the data straight into the database without instantiating the model. 

So there are a couple options, including reindexing the model manually as per your recommendation like this:

```
class ActiveSupport::TestCase
  parallelize_setup do |worker|
    Searchkick.index_suffix = worker

    # reindex models
    Product.reindex

    # and disable callbacks
    Searchkick.disable_callbacks
  end
end
```
And use:
```
class ProductTest < ActiveSupport::TestCase
  def setup
    # reindex models
    Product.reindex
    Searchkick.enable_callbacks
    
    @product = products(:apple)
  end

  def teardown
    Searchkick.disable_callbacks
  end

  def test_search
    assert_equal [@product.name], Product.search("apple").map(&:name)
  end
end
```
