### ISSUE TITLE
search_after support in the searchkick

### ISSUE THREAD

**Issue by kshtzkr** [ankane/searchkick#1599]
**First**
Search existing issues to see if it’s been discussed.

**Is your feature request related to a problem? Please describe.**
In elastic official documentation they says
`We no longer recommend using the scroll API for deep pagination. If you need to preserve the index state while paging through more than 10,000 hits, use the [search_after](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after) parameter with a point in time (PIT).`

**Describe the solution you'd like**
Can we add a support in the search so, support the search_after functionality of the elastic as many of us are using scroll api which isn't a efficient mechanism to traverse all the data inside a database

**Additional context**
Add any other context.

**Comment by ankane** [comment]
Hey @kshtzkr, thanks for the suggestion. Both search_after and point in time are currently available with `body_options`. I added a few [test cases](https://github.com/ankane/searchkick/blob/909de90bb8256273a823fb096e473c01601edaff/test/pagination_test.rb#L159-L222) to show how to use them.

Can you give more details on the API you'd like to see?

**Comment by julianxhuntclub** [comment]
Hi Arkane, I'm currently struggling to get PIT and search_after working with SearchKick. I keep getting the following error: `"Validation Failed: 1: [indices] cannot be used with point in time. Do not specify any index with point in time.;"}]`

I assume this is because the index is "double dipping" and Elastic doesn't like that? We are running version 4.6.1 .
