### ISSUE TITLE
search in two combined fields

### ISSUE THREAD

**Issue by cusaro** [ankane/searchkick#211]
Hello,

I have the fields firstname and lastname. Now i want to search over this two fields for the fullname.

i tryed:

``` ruby
Person.search(query:{multi_match:{query:"John Doe", fields:[ "firstname", "lastname" ] }})
```

but i does not work. What is the right approach here?

**Comment by ledermann** [comment]
What would you suggest for the following (similiar) situation using latest Elasticsearch 2.1.0:

````ruby
class Document < ActiveRecord::Base
  searchkick word_start: [ :title, :content ], 
             highlight:  [ :title, :content ]

  def search_data
    { title:   title,
      content: content,
    }
  end
end

doc = Document.create! title: 'foo', content: 'bar baz'

Document.search "foo bar"
# => doc is found, ok
````

So far, so good. But now I want to use boosting and highlighting:

````ruby
Document.search "foo bar", fields: [ 'title^20', 'content'], highlight: true
# => nothing is found
````

How is possible to search for multiple terms which may exist in different fields? If a cross-field multi match is needed, how can this be invoked by Searchkick?

Combining `content` and `title` into one field seems no solution for me, because it makes boosting impossible.

**Comment by ankane** [comment]
Searchkick doesn't support for cross fields at the moment, so you'll need to [customize the query](https://github.com/ankane/searchkick#advanced-search) yourself.  I'm happy to accept a pull request with this functionality to make it easier for others.

**Comment by williamweckl** [comment]
[Here][1] is an example how you could customize the query to do it. Hope it helps.

[1]:http://stackoverflow.com/a/34266548/2767026
