### ISSUE TITLE
Searchkick with Bonsai on Heroku

### ISSUE THREAD

**Issue by rdlh** [ankane/searchkick#409]
Hi!

Bonsai support just told me to open an issue here because some searchkick is functions are not working on production.

> A few weeks ago, a vulnerability was discovered that would have allowed an attacker to escape Groovy's sandbox and run arbitrary code on the server. In response, we disabled dynamic Groovy scripting to protect users. That is probably not disabled on your local instance, which is why the behavior is different.

> The ideal solution there is to change the script to Lucene expressions, which is now the default. Lucene doesn't have a `log` function, but it does have an equivalent `ln`. So changing log to ln should clear up that error on bonsai: `"script":"1.0 * ln(doc[\"trips_count\"].value + 2.718281828)"`

My gem versions:
* `elasticsearch-model-0.1.6`
* `elasticsearch-rails-0.1.6`
* `bonsai-elasticsearch-rails-0.0.4`
* `Searchkick.server_version` => `1.4.4`

Is that possible to update the gem with this update ?
Thanks in advance

**Comment by rdlh** [comment]
[Looks like this line](https://github.com/ankane/searchkick/blob/master/lib/searchkick/query.rb#L179)

**Comment by robsears** [comment]
Bonsai support here. There are actually two different issues at play. The proximate one is that Searchkick's logic seems to be broken in lib/searchkick/query.rb. This is the code block that involves query boosting (around L179):

```
if below12
  {script_score: {script: "#{value[:factor].to_f} * log(doc['#{field}'].value + 2.718281828)"}}
else
  {field_value_factor: {field: field, factor: value[:factor].to_f, modifier: "ln2p"}}
end
```

The `below12` variable is assigned at line 18 as:

```
below12 = Gem::Version.new(Searchkick.server_version) < Gem::Version.new("1.2")
below14 = Gem::Version.new(Searchkick.server_version) < Gem::Version.new("1.4")
```

Tracing through the code, it looks like Searchkick is trying to identify which version of Elastic is in use, and select a boosting method accordingly. `Searchkick.server_version` correctly returns 1.4.4 (the version bonsai is currently running in production), so `below12` should be returning `false` and using the non-scripting boosting method. However, this isn't the case.

The secondary issue is that Elastic has dropped Groovy as a default in 1.4.4+ due to some sandboxing vulnerabilities. It would be nice if Searchkick defaulted to Lucene expressions (which are capable of boosting just like Groovy), or at least offered a configuration option for this.

**Comment by DanBradbury** [comment]
Since the `below` methods have been updated (https://github.com/ankane/searchkick/blob/master/lib/searchkick/query.rb#L642-L656) can we close this issue? 

Currently running into some other bonsai issues which led me here and after a bit of digging it looks like this has been addressed..

**Comment by ankane** [comment]
Cleaning up issues. Please reopen with more details if it's still an issue.
