### ISSUE TITLE
turning off the synonyms

### ISSUE THREAD

**Issue by jorge8989** [ankane/searchkick#664]
Is there a way of turning off the synonyms ?

i needed the 'phrase matches' options, but that feature is not released yet, so i tried with the master branch, but i didn't work for some reason.
so I'm working with this fork https://github.com/jorge8989/searchkick

i'm using 
`
match_phrase: true
`
The 'phrase matches' is working.

but the synonyms don't let me get the results that i expected.

When i search for "web developer" 

`
Candidate.search('web developer', match_phrase: true)
`
i get also results for the phrase "web development", i think this is because of the synonyms, i would love to avoid this behavior.

is there a way to do that?
i'd like to add that feature

 thanks.

**Comment by ankane** [comment]
Hey @jorge8989, this is likely due to stemming (unless you're specifying synonyms). There's no way to turn off stemming at the moment, but happy to accept a PR for it. Here's the file where you'd want to make the changes: https://github.com/ankane/searchkick/blob/master/lib/searchkick/index_options.rb

**Comment by ankane** [comment]
Closing in favor of #803
