### ISSUE TITLE
Consolidate Indeces

### ISSUE THREAD

**Issue by mrjlynch** [ankane/searchkick#671]
Is it possible to consolidate indexes from several different models? This is as opposed to an indices per model approach, which is not appropriate where there are a small number of documents, though a large number of models. 

Such an approach is described [here](https://docs.bonsai.io/docs/reducing-shard-usage) under "Consolidate your data"

**Comment by ZempTime** [comment]
I'm running into this, too, also with Bonsai ElasticSearch on Heroku.

They charge by both memory and # of shards. SearchKick, by default, seems to do two shards per model (and the replication is good!). Bonsai's free tier only allows for two shards, so one replicated index (much like the setup in the link). In the case of the site I'm working on, I have a small amount of fixed data that I need to demonstrate some basic search functionality on for staging, so being able to easily combine those would save hosting costs immediately since staging could become free in perpetuity.

Currently I'm trying to get everything to operate off of one index and utilize the `_type` that's automatically stored, but when I do this ever time I reindex it overwrites the entire index such that only one kind of model is allowed to be stored at once.

At what an API for this might look like, perhaps something like:

config/initializers/searchkick.rb
```ruby
Searchkick.use_single_index = true
# perhaps default to: "#{Rails.application.class.parent_name.snake_case}_{Rails.env}"
# ex: appname_development
```

If this is way outside the intent or scope of SearchKick I could switch over to the official client. But I really really like SearchKick, so if there's a way I can help, then please ask! Not confident I can submit a great PR, but I'll give it a shot, and any guidance is appreciated.

**Comment by ZempTime** [comment]
Follow-up: @mrjlynch 

you can configure the # of shards used via the searchkick method in your model:

```
class Something < ApplicationRecord
  searchkick settings: { number_of_shards: 1}
end
```

Secondly, compare how much it would cost (your hourly rate or whatever) to do all this configuration. Chances are, its just not worth it when you factor in people costs. Better just to pony up so you don't have to do devops or whatever.

If this sort of functionality were here, I'd use it and get the savings. But I think ultimately its simply the best choice to use SearchKick and pony up for hosting costs/pay less people costs!

**Comment by ankane** [comment]
Searchkick's current reindex process is heavily dependent on one index per model.  There aren't any plans right now to support multiple models in the same index.
