### ISSUE TITLE
Add support for geo_shape

### ISSUE THREAD

**Issue by ankane** [ankane/searchkick#765]
Proposal

```ruby
class Product
  searchkick geo_shape: {
    boundingbox: {tree: "quadtree", precision: "1km"}
  }

  def search_data
    {
      boundingbox: {type: "envelope", coordinates: [{lat: 1, lon: 2}, {lat: 3, lon: 4}, {lat: 5, lon: 6}]}
    }
  end
end
```

And search with:

```ruby
Product.search("*", where: {boundingbox: {geo_shape: {type: "circle", coordinates: [{lat: 2, lon: 3}], radius: "100m"}}}})
```

Would love a PR. Thanks to #355 #361 for getting the conversation started.

**Comment by will-r** [comment]
#789 is an implementation of this interface. There is a little bit of sugar to support envelope corners and lat/lon objects, but otherwise we are just passing through geoJSON. Tests and readme section are included.

I think it's a general solution but of course we are also working to our own particular requirements. Please let me know if you would like anything to work differently.

**Comment by ankane** [comment]
Merged!
