### ISSUE TITLE
Search with Named Scope and pagination

### ISSUE THREAD

**Issue by Xosmond** [ankane/searchkick#812]
I trying to make a filter on the search so i read issue:140 but it seems it doesn't work.

This way keep sending all records:
@users = User.dealers.search query, page: params[:page], per_page: 12

This works buts it's ugly:
@users = User.search query, where:{role: "Dealer"}, page: params[:page], per_page: 12

I can't do this way because i need the pagination:
@users = User.search query, page: params[:page], per_page: 12
@users = @users.records.dealers

If you know another way please tell me.

Reference: https://github.com/ankane/searchkick/issues/140

**Comment by ankane** [comment]
Hey @Xosmond, your 2nd example is how you should do it. Searchkick doesn't support ActiveRecord or Mongoid scopes because there's not a great way to do this performantly.

It'd need to fetch all ids for the scope before calling ES and add those ids to the search query, which would be expensive for scopes with a large number of results, as this can't be paginated.

**Comment by Xosmond** [comment]
Your right, i was thinking about it. Thanks anyway.
