### ISSUE TITLE
match: :phrase alongside operator: "or"

### ISSUE THREAD

**Issue by cmalpeli** [ankane/searchkick#886]
Is there a way to match using both `match: :phrase` as well as `operator: "or"`?

Say I search for "one two three".  If that exact phrase appears, I'd like that to rank first, but but still match again docs that contain any of the words "one", "two" or "three".

It seems I can get the "or" to work, but then if I introduce `match: :phrase` results are limited to ONLY the ones with the exact phrase match.

Thanks!

**Comment by ankane** [comment]
Hey @cmalpeli, it sounds like you want to boost by a phrase match rather than limit it to a phrase match as the example above does. Naturally, a result with "one", "two", and three" will do better than a result with "one" and "two", so it's only really useful if you're trying to boost "one two three" over "three two one" or "two three one". Searchkick doesn't support this now, but I don't think it'd be super hard to add if it's practically useful. Do you have a few real-world examples of where this distinction is necessary?

**Comment by cmalpeli** [comment]
Thanks @ankane!  So, in thinking about my problem, and your response, yes - I guess I'd want to boost the phrase match.  I think that my underlying issue is that I have a boost on another column, which is pushing content that does have an exact match below content that has a lesser match, but gets bumped due to the boost.  So I guess ideally I would be able to boost both a `match: :phrase`, as well as this other column.  Make sense?

**Comment by ankane** [comment]
In that case, I'd try changing the `factor` of the boost from the other column if it's too strong.
