### ISSUE TITLE
support for multiple ranges in where?

### ISSUE THREAD

**Issue by michelson** [ankane/searchkick#979]
Hi people, I'm trying to support multiple ranges with searchkick.

my options are:

```
options = 
{:start_date_relative_year=>
  [{:gte=>"2010", :lte=>"2016"},
   {:gte=>"2000", :lte=>"2009"},
   {:gte=>"1990", :lte=>"1999"}]}
```

then in the search `Model.search("*", where: options )` but I got an error `number_format_exception","reason":"For input string: \"{\""}`

how can I support this with searchkick?

best

**Comment by rafaelsales** [comment]
@michelson 
```ruby
where: {
  _or: [
    { start_date_relative_year: { gte: "2010", lte: "2016" } },
    { start_date_relative_year: { gte: "2000", lte: "2009" } },
    { start_date_relative_year: { gte: "1990", lte: "1999" } },
  ]
}
```

**Comment by ankane** [comment]
Hey @rafaelsales, thanks for the assist 👍

**Comment by shantilal-narola** [comment]
Hi, I'm using Searchkick in my Rails 5 application and I'm trying to support ranges and boolean term condition in app. 

My range query with `where` like: 
`Pet.search '*',
     where: { 
          _or:  [ { age_years: { gte: "5", lte: "7" } }  ] 
      }`

But I got an error as below:
`"caused_by":{"type":"illegal_argument_exception","reason":"Cannot search on field [age_years] since it is not indexed."}`

Also I've tried with `aggs` query like: 
` options = {:aggs=>{:age_years=>{:ranges=>[{:from=>7, :to=> 12}]}}}
    Pet.search("*", options)`

But I got an error as below:
`{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [age_years] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}`

how can I fix this with searchkick?

**Comment by rafaelsales** [comment]
@shantilal-narola it seems like your field can't be used on search/query _since it is not indexed_. If you could share your index definition in the model as well as the model schema, I think it would make it easier to help here...
